
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;




public class BrightContrastEffect : ShaderEffect
{

    public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(BrightContrastEffect), 0);

    public static readonly DependencyProperty BrightnessProperty = DependencyProperty.Register("Brightness", typeof(double), typeof(BrightContrastEffect), new PropertyMetadata(((double)(0D)), PixelShaderConstantCallback(0)));

    public static readonly DependencyProperty PosOfHotSpotProperty = DependencyProperty.Register("PosOfHotSpot", typeof(double), typeof(BrightContrastEffect), new PropertyMetadata(((double)(0D)), PixelShaderConstantCallback(2)));

    public BrightContrastEffect(string pathToPSFile)
    {
        this.PixelShader = new PixelShader();
        this.PixelShader.UriSource = new Uri(pathToPSFile);

        this.UpdateShaderValue(InputProperty);
        this.UpdateShaderValue(BrightnessProperty);
        this.UpdateShaderValue(PosOfHotSpotProperty);
    }

    public Brush Input
    {
        get
        {
            return ((Brush)(this.GetValue(InputProperty)));
        }
        set
        {
            this.SetValue(InputProperty, value);
        }
    }

    public double Brightness
    {
        get
        {
            return ((double)(this.GetValue(BrightnessProperty)));
        }
        set
        {
            this.SetValue(BrightnessProperty, value);
        }
    }

    public double PosOfHotSpot
    {
        get
        {
            return ((double)(this.GetValue(PosOfHotSpotProperty)));
        }
        set
        {
            this.SetValue(PosOfHotSpotProperty, value);
        }
    }
}
